# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestExploreTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_exploreTest(self):
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(1296, 688)
    self.driver.find_element(By.CSS_SELECTOR, ".active > .nav-link").click()
    self.driver.find_element(By.LINK_TEXT, "About us").click()
    self.driver.find_element(By.CSS_SELECTOR, "#videoModal .btn").click()
    self.driver.find_element(By.LINK_TEXT, "Contact").click()
    element = self.driver.find_element(By.LINK_TEXT, "Contact")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#exampleModal .btn-secondary").click()
    self.driver.find_element(By.ID, "nameofuser").click()
    self.driver.close()
  
